let strip = neopixel.create(DigitalPin.P1, 7, NeoPixelMode.RGB)
strip.setBrightness(255)
basic.forever(function () {
    strip.setPixelColor(0, neopixel.colors(NeoPixelColors.Red))
    strip.setPixelColor(1, neopixel.colors(NeoPixelColors.Red))
    strip.setPixelColor(2, neopixel.colors(NeoPixelColors.Red))
    strip.show()
    basic.pause(500)
    strip.clear()
    strip.show()
    strip.setPixelColor(4, neopixel.colors(NeoPixelColors.Blue))
    strip.setPixelColor(5, neopixel.colors(NeoPixelColors.Blue))
    strip.setPixelColor(6, neopixel.colors(NeoPixelColors.Blue))
    strip.show()
    basic.pause(500)
    strip.clear()
    strip.show()
})
basic.forever(function () {
    music.playMelody("C5 C C5 C C5 C C5 C ", 120)
})
